apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: springapp
data:
  POSTGRES_USER: app
  POSTGRES_DB: aplikacija

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: springapp
type: Opaque
data:
  POSTGRES_PASSWORD: MTIzNDU=
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgre-pvc
  namespace: springapp
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgre-service
  namespace: springapp
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgre
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgre
  namespace: springapp
spec:
  serviceName: postgre-service
  selector:
    matchLabels:
      app: postgre
  replicas: 1
  template:
    metadata:
      labels:
        app: postgre
        namespace: springapp
    spec:
      containers:
        - name: postgre
          image: kristina212006/postgre:v61
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: dbdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: postgre-pvc
